name: trello_to_github
description: Open-source and collaborative tool for migrating Trello cards of a board to GitHub issues of a repository.

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  beamer: ^1.1.0
  file_picker: ^4.2.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  github: ^8.2.5
  json_annotation: ^4.4.0

dev_dependencies:
  build_runner: ^2.1.5
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.1
  lint: ^1.8.1

flutter:
  uses-material-design: true
