name: trello_to_github
description: Open-source and collaborative tool for migrating Trello cards of a board to GitHub issues of a repository.

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  beamer: ^1.1.0
  dio: ^4.0.4
  file_picker: ^4.2.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  fpdart: ^0.0.12
  get_it: ^7.2.0
  github: ^8.2.5
  hive_flutter: ^1.1.0
  injectable: ^1.5.0
  intl: ^0.17.0
  json_annotation: ^4.4.0
  pretty_dio_logger: ^1.2.0-beta-1
  retrofit: ^3.0.0
  url_launcher: ^6.0.17

dev_dependencies:
  build_runner: ^2.1.5
  flutter_test:
    sdk: flutter
  injectable_generator: ^1.5.2
  json_serializable: ^6.1.1
  lint: ^1.8.1
  retrofit_generator: ^3.0.0+2

flutter:
  uses-material-design: true
